# -*- coding: utf-8 -*-
"""Desi Restaurant System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRNd8_kWHiHHNfYhvrGjuiZVyhsit5vR

## Desi Restaurant System

MENU FUNCTION (Basics)
       This function takes a food item as input and returns the appropriate status message for that item.
"""

def menu(item):
    # Convert to lowercase so "Biryani" and "biryani" both work
    item = item.lower()

    if item == "karhai":
        return "Karhai is cooking 🍳"
    elif item == "biryani":
        return "Biryani is ready 🍛"
    elif item == "bbq":
        return "BBQ is grilled 🔥"
    elif item == "chai":
        return "Chai is served ☕"
    else:
        return "Item not available ❌"

"""# Testing

"""

print("       MENU FUNCTION TEST")
print(menu("karhai"))
print(menu("biryani"))
print(menu("bbq"))
print(menu("chai"))
print(menu("burger"))

print()

"""        Q2. CUSTOMER SERVING SYSTEM (Loop)
        We loop through 5 customers, take their food order as input,call the menu() function, and print the result.



"""

print("       CUSTOMER SERVING SYSTEM")

for i in range(1, 6):                          # Loop from customer 1 to 5
    item = input(f"Customer {i} — Enter food item: ")
    result = menu(item)
    print(f"Customer {i} ordered {item.lower()}, {result}")

print()

"""
        KARHAI SPICE SYSTEM (If-Else Function)
        This function takes a spice level and returns the
        type of karhai based on the spice level.
"""

def karhai(spice_level):
    spice_level = spice_level.lower()

    if spice_level == "high":
        return "Very Spicy Karhai 🌶️🔥"
    elif spice_level == "medium":
        return "Normal Karhai 🍳"
    elif spice_level == "low":
        return "Mild Karhai"
    else:
        return "Invalid input!"

"""### Testing

"""

print("       KARHAI SPICE SYSTEM TEST")


print(karhai("high"))
print(karhai("medium"))
print(karhai("low"))
print(karhai("extra"))

print()

"""        BBQ PLATTER SYSTEM (Function + If-Else)
        This function takes number of pieces and returns
        the platter size based on quantity rules.

"""

def bbq(pieces):
    if pieces >= 10:
        return "Full BBQ Platter 🔥"
    elif pieces >= 5:
        return "Half BBQ Platter"
    else:
        return "Small BBQ Plate!"

"""### Testing

"""

print("       BBQ PLATTER SYSTEM TEST")


print(f"10 pieces , {bbq(10)}")
print(f"7 pieces  , {bbq(7)}")
print(f"3 pieces  , {bbq(3)}")

print()

"""      CHAI SYSTEM (Function + If-Else)
      This function takes a sugar value (0, 1, or 2+)
      and returns the type of chai accordingly.

"""

def chai(sugar):
    if sugar == 0:
        return "No Sugar Chai ☕"
    elif sugar == 1:
        return "Normal Chai ☕"
    elif sugar >= 2:
        return "Sweet Chai 🍬☕"
    else:
        return "Invalid sugar level"

"""### Testing

"""

print("       CHAI SYSTEM TEST")


print(f"Sugar 0 → {chai(0)}")
print(f"Sugar 1 → {chai(1)}")
print(f"Sugar 2 → {chai(2)}")
print(f"Sugar 4 → {chai(4)}")

print()

"""      FINAL TASK — DESI RESTAURANT MANAGEMENT SYSTEM
      This is the complete combined system that:
      - Loops through 5 customers
      - Takes their food order
      - Calls the correct function based on order
      - Prints a neat, formatted output for each customer

"""

print("   🍽️  DESI RESTAURANT MANAGEMENT SYSTEM  🍽️")

for i in range(1, 6):                          # Loop for 5 customers
    print(f"\n👤 Customer {i}")
    print("-" * 40)

    # Step 1: Take the food item order
    item = input(f"  Enter food item (karhai/biryani/bbq/chai): ").lower()

    # Step 2: Call the menu() function for this item
    menu_result = menu(item)
    print(f"  Menu Status: {menu_result}")

    # Step 3: Based on the item, call extra functions

    if item == "karhai":
        # If item is karhai , ask for spice level
        spice = input("  Enter spice level (high/medium/low): ")
        karhai_result = karhai(spice)
        print(f"  Karhai Type: {karhai_result}")

    elif item == "bbq":
        # If item is bbq , ask for number of pieces
        pieces = int(input("  Enter number of BBQ pieces: "))
        bbq_result = bbq(pieces)
        print(f"  BBQ Platter: {bbq_result}")

    elif item == "chai":
        # If item is chai → ask for sugar level
        sugar = int(input("  Enter sugar level (0 / 1 / 2+): "))
        chai_result = chai(sugar)
        print(f"  Chai Type: {chai_result}")

    # biryani has no extra step — menu() result is enough

    print("-" * 40)

print()

print("Thank you! All customers have been served.")